const keyboardDataObject = 
[
    [
      {
        keyCode: 'Backquote',
        hasFunction: false,
        writing: { en: {true : '~', false : '`'}, ru: {true : 'Ё', false : 'ё'} },
        widthClass: 'keyboard-key-type1',
      },
      {
        keyCode: 'Digit1',
        hasFunction: false,
        writing: { en: {true : '!', false : '1'}, ru: {true : '!', false : '1'} },
        widthClass: 'keyboard-key-type1',
      },
      {
        keyCode: 'Digit2',
        hasFunction: false,
        writing: { en: {true : '@', false : '2'}, ru: {true : '@', false : '2'} },
        widthClass: 'keyboard-key-type1',
      },
      {
        keyCode: 'Digit3',
        hasFunction: false,
        writing: { en: {true : '#', false : '3'}, ru: {true : '#', false : '3'} },
        widthClass: 'keyboard-key-type1',
      },
      {
        keyCode: 'Digit4',
        hasFunction: false,
        writing: { en: {true : '$', false : '4'}, ru: {true : '$', false : '4'} },
        widthClass: 'keyboard-key-type1',
      },
      {
        keyCode: 'Digit5',
        hasFunction: false,
        writing: { en: {true : '%', false : '5'}, ru: {true : '%', false : '5'} },
        widthClass: 'keyboard-key-type1',
      },
      {
        keyCode: 'Digit6',
        hasFunction: false,
        writing: { en: {true : '^', false : '6'}, ru: {true : '^', false : '6'} },
        widthClass: 'keyboard-key-type1',
      },
      {
        keyCode: 'Digit7',
        hasFunction: false,
        writing: { en: {true : '&', false : '7'}, ru: {true : '&', false : '7'} },
        widthClass: 'keyboard-key-type1',
      },
      {
        keyCode: 'Digit8',
        hasFunction: false,
        writing: { en: {true : '*', false : '8'}, ru: {true : '*', false : '8'} },
        widthClass: 'keyboard-key-type1',
      },
      {
        keyCode: 'Digit9',
        hasFunction: false,
        writing: { en: {true : '(', false : '9'}, ru: {true : '(', false : '9'} },
        widthClass: 'keyboard-key-type1',
      },
      {
        keyCode: 'Digit0',
        hasFunction: false,
        writing: { en: {true : ')', false : '0'}, ru: {true : ')', false : '0'} },
        widthClass: 'keyboard-key-type1',
      },
      {
        keyCode: 'Minus',
        hasFunction: false,
        writing: { en: {true : '_', false : '-'}, ru: {true : '_', false : '-'} },
        widthClass: 'keyboard-key-type1',
      },
      {
        keyCode: 'Equal',
        hasFunction: false,
        writing: { en: {true : '+', false : '='}, ru: {true : '+', false : '='} },
        widthClass: 'keyboard-key-type1',
      },
      {
        keyCode: 'Backspace',
        hasFunction: true,
        writing: { en: {true : 'Back', false : 'Back'}, ru: {true : 'Back', false : 'Back'} },
        widthClass: 'keyboard-key-type2',
      },
      {
        keyCode: 'Delete',
        hasFunction: true,
        writing: { en: {true : 'Del', false : 'Del'}, ru: {true : 'Del', false : 'Del'} },
        widthClass: 'keyboard-key-type2',
      },
    ],
    [
      {
        keyCode: 'Tab',
        hasFunction: true,
        writing: { en: {true : 'Tab', false : 'Tab'}, ru: {true : 'Tab', false : 'Tab'} },
        widthClass: 'keyboard-key-type3',
      },
      {
        keyCode: 'KeyQ',
        hasFunction: false,
        writing: { en: {true : 'Q', false : 'q'}, ru: {true : 'Й', false : 'й'} },
        widthClass: 'keyboard-key-type1',
      },
      {
        keyCode: 'KeyW',
        hasFunction: false,
        writing: { en: {true : 'W', false : 'w'}, ru: {true : 'Ц', false : 'ц'} },
        widthClass: 'keyboard-key-type1',
      },
      {
        keyCode: 'KeyE',
        hasFunction: false,
        writing: { en: {true : 'E', false : 'e'}, ru: {true : 'У', false : 'у'} },
        widthClass: 'keyboard-key-type1',
      },
      {
        keyCode: 'KeyR',
        hasFunction: false,
        writing: { en: {true : 'R', false : 'r'}, ru: {true : 'К', false : 'к'} },
        widthClass: 'keyboard-key-type1',
      },
      {
        keyCode: 'KeyT',
        hasFunction: false,
        writing: { en: {true : 'T', false : 't'}, ru: {true : 'Е', false : 'е'} },
        widthClass: 'keyboard-key-type1',
      },
      {
        keyCode: 'KeyY',
        hasFunction: false,
        writing: { en: {true : 'Y', false : 'y'}, ru: {true : 'Н', false : 'н'} },
        widthClass: 'keyboard-key-type1',
      },
      {
        keyCode: 'KeyU',
        hasFunction: false,
        writing: { en: {true : 'U', false : 'u'}, ru: {true : 'Г', false : 'г'} },
        widthClass: 'keyboard-key-type1',
      },
      {
        keyCode: 'KeyI',
        hasFunction: false,
        writing: { en: {true : 'I', false : 'i'}, ru: {true : 'Ш', false : 'ш'} },
        widthClass: 'keyboard-key-type1',
      },
      {
        keyCode: 'KeyO',
        hasFunction: false,
        writing: { en: {true : 'O', false : 'o'}, ru: {true : 'Щ', false : 'щ'} },
        widthClass: 'keyboard-key-type1',
      },
      {
        keyCode: 'KeyP',
        hasFunction: false,
        writing: { en: {true : 'P', false : 'p'}, ru: {true : 'З', false : 'з'} },
        widthClass: 'keyboard-key-type1',
      },
      {
        keyCode: 'BracketLeft',
        hasFunction: false,
        writing: { en: {true : '[', false : '{'}, ru: {true : 'Х', false : 'х'} },
        widthClass: 'keyboard-key-type1',
      },
      {
        keyCode: 'BracketRight',
        hasFunction: false,
        writing: { en: {true : ']', false : '}'}, ru: {true : 'Ъ', false : 'ъ'} },
        widthClass: 'keyboard-key-type1',
      },
      {
        keyCode: 'Backslash',
        hasFunction: false,
        writing: { en: {true : '|', false : '\\'}, ru: {true : '/', false : '\\'} },
        widthClass: 'keyboard-key-type1',
      },
    ],
    [
      {
        keyCode: 'CapsLock',
        hasFunction: true,
        writing: { en: {true : 'Caps', false : 'Caps'}, ru: {true : 'Caps', false : 'Caps'} },
        widthClass: 'keyboard-key-type3',
      },
      {
        keyCode: 'KeyA',
        hasFunction: false,
        writing: { en: {true : 'A', false : 'a'}, ru: {true : 'Ф', false : 'ф'} },
        widthClass: 'keyboard-key-type1',
      },
      {
        keyCode: 'KeyS',
        hasFunction: false,
        writing: { en: {true : 'S', false : 's'}, ru: {true : 'Ы', false : 'ы'} },
        widthClass: 'keyboard-key-type1',
      },
      {
        keyCode: 'KeyD',
        hasFunction: false,
        writing: { en: {true : 'D', false : 'd'}, ru: {true : 'В', false : 'в'} },
        widthClass: 'keyboard-key-type1',
      },
      {
        keyCode: 'KeyF',
        hasFunction: false,
        writing: { en: {true : 'F', false : 'f'}, ru: {true : 'A', false : 'a'} },
        widthClass: 'keyboard-key-type1',
      },
      {
        keyCode: 'KeyG',
        hasFunction: false,
        writing: { en: {true : 'G', false : 'g'}, ru: {true : 'П', false : 'п'} },
        widthClass: 'keyboard-key-type1',
      },
      {
        keyCode: 'KeyH',
        hasFunction: false,
        writing: { en: {true : 'H', false : 'h'}, ru: {true : 'Р', false : 'р'} },
        widthClass: 'keyboard-key-type1',
      },
      {
        keyCode: 'KeyJ',
        hasFunction: false,
        writing: { en: {true : 'J', false : 'j'}, ru: {true : 'О', false : 'о'} },
        widthClass: 'keyboard-key-type1',
      },
      {
        keyCode: 'KeyK',
        hasFunction: false,
        writing: { en: {true : 'K', false : 'k'}, ru: {true : 'Л', false : 'л'} },
        widthClass: 'keyboard-key-type1',
      },
      {
        keyCode: 'KeyL',
        hasFunction: false,
        writing: { en: {true : 'L', false : 'l'}, ru: {true : 'Д', false : 'д'} },
        widthClass: 'keyboard-key-type1',
      },
      {
        keyCode: 'Semicolon',
        hasFunction: false,
        writing: { en: {true : ':', false : ';'}, ru: {true : 'Ж', false : 'ж'} },
        widthClass: 'keyboard-key-type1',
      },
      {
        keyCode: 'Quote',
        hasFunction: false,
        writing: { en: {true : '"', false : "'"}, ru: {true : 'Э', false : 'э'} },
        widthClass: 'keyboard-key-type1',
      },
      {
        keyCode: 'Enter',
        hasFunction: true,
        writing: { en: {true : 'Enter', false : 'Enter'}, ru: {true : 'Enter', false : 'Enter'} },
        widthClass: 'keyboard-key-type3',
      },
    ],
    [
      {
        keyCode: 'ShiftLeft',
        hasFunction: true,
        writing: { en: {true : 'Shift', false : 'Shift'}, ru: {true : 'Shift', false : 'Shift'} },
        widthClass: 'keyboard-key-type3',
      },
      {
        keyCode: 'KeyZ',
        hasFunction: false,
        writing: { en: {true : 'Z', false : 'z'}, ru: {true : 'Я', false : 'я'} },
        widthClass: 'keyboard-key-type1',
      },
      {
        keyCode: 'KeyX',
        hasFunction: false,
        writing: { en: {true : 'X', false : 'x'}, ru: {true : 'Ч', false : 'ч'} },
        widthClass: 'keyboard-key-type1',
      },
      {
        keyCode: 'KeyC',
        hasFunction: false,
        writing: { en: {true : 'C', false : 'c'}, ru: {true : 'С', false : 'с'} },
        widthClass: 'keyboard-key-type1',
      },
      {
        keyCode: 'KeyV',
        hasFunction: false,
        writing: { en: {true : 'V', false : 'v'}, ru: {true : 'М', false : 'м'} },
        widthClass: 'keyboard-key-type1',
      },
      {
        keyCode: 'KeyB',
        hasFunction: false,
        writing: { en: {true : 'B', false : 'b'}, ru: {true : 'И', false : 'и'} },
        widthClass: 'keyboard-key-type1',
      },
      {
        keyCode: 'KeyN',
        hasFunction: false,
        writing: { en: {true : 'N', false : 'n'}, ru: {true : 'Т', false : 'т'} },
        widthClass: 'keyboard-key-type1',
      },
      {
        keyCode: 'KeyM',
        hasFunction: false,
        writing: { en: {true : 'M', false : 'm'}, ru: {true : 'Ь', false : 'ь'} },
        widthClass: 'keyboard-key-type1',
      },
      {
        keyCode: 'Comma',
        hasFunction: false,
        writing: { en: {true : '<', false : ','}, ru: {true : 'Б', false : 'б'} },
        widthClass: 'keyboard-key-type1',
      },
      {
        keyCode: 'Period',
        hasFunction: false,
        writing: { en: {true : '>', false : '.'}, ru: {true : 'Ю', false : 'ю'} },
        widthClass: 'keyboard-key-type1',
      },
      {
        keyCode: 'Slash',
        hasFunction: false,
        writing: { en: {true : '?', false : '/'}, ru: {true : ',', false : '.'} },
        widthClass: 'keyboard-key-type1',
      },
      {
        keyCode: 'ArrowUp',
        hasFunction: true,
        writing: { en: {true : '⯅', false : '⯅'}, ru: {true : '⯅', false : '⯅'} },
        widthClass: 'keyboard-key-type1',
      },
      {
        keyCode: 'ShiftRight',
        hasFunction: true,
        writing: { en: {true : 'Shift', false : 'Shift'}, ru: {true : 'Shift', false : 'Shift'} },
        widthClass: 'keyboard-key-type3',
      },
    ],
    [
      {
        keyCode: 'ControlLeft',
        hasFunction: true,
        writing: { en: {true : 'Ctrl', false : 'Ctrl'}, ru: {true : 'Ctrl', false : 'Ctrl'} },
        widthClass: 'keyboard-key-type2',
      },
      {
        keyCode: 'AltLeft',
        hasFunction: true,
        writing: { en: {true : 'Alt', false : 'Alt'}, ru: {true : 'Alt', false : 'Alt'} },
        widthClass: 'keyboard-key-type2',
      },
      {
        keyCode: 'Space',
        hasFunction: false,
        writing: { en: {true : ' ', false : ' '}, ru: {true : ' ', false : ' '} },
        widthClass: 'keyboard-key-space',
      },
      {
        keyCode: 'AltRight',
        hasFunction: true,
        writing: { en: {true : 'Alt', false : 'Alt'}, ru: {true : 'Alt', false : 'Alt'} },
        widthClass: 'keyboard-key-type2',
      },
      {
        keyCode: 'ControlRight',
        hasFunction: true,
        writing: { en: {true : 'Ctrl', false : 'Ctrl'}, ru: {true : 'Ctrl', false : 'Ctrl'} },
        widthClass: 'keyboard-key-type2',
      },
      {
        keyCode: 'ArrowLeft',
        hasFunction: true,
        writing: { en: {true : '⯇', false : '⯇'}, ru: {true : '⯇', false : '⯇'} },
        widthClass: 'keyboard-key-type1',
      },
      {
        keyCode: 'ArrowDown',
        hasFunction: true,
        writing: { en: {true : '⯆', false : '⯆'}, ru: {true : '⯆', false : '⯆'} },
        widthClass: 'keyboard-key-type1',
      },
      {
        keyCode: 'ArrowRight',
        hasFunction: true,
        writing: { en: {true : '⯈', false : '⯈'}, ru: {true : '⯈', false : '⯈'} },
        widthClass: 'keyboard-key-type1',
      },
    ],
];

export {keyboardDataObject};